version: "3.0"
services:
  influx:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - influxdata:/var/lib/influx.db
    ports:
      - "8086:8086"
  nats:
    image: nats:latest
  gateway:
    build:
      context: .
    image: service-gateway
    env_file: docker-compose.env
    environment:
      NODEID: "node-gateway"
      SERVICES: gateway
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - nats
  data:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-data"
      SERVICES: data
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      INFLUXDB_DATABASE: air_emission
      INFLUXDB_HOST: influx
    links:
      - analytics
    depends_on:
      - nats
      - influx
  device:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      NODEID: "node-device"
      SERVICES: device
    depends_on:
      - nats
  # grafana:
  #   ports:
  #     - 4200:3000
  #   image: grafana/grafana:3.1.1
  #   depends_on:
  #     - influx
  #   links:
  #     - influx
  #   volumes:
  #     - influxdata:/var/lib/influx.db
  analytics:
    build:
      context: ./analytics
    image: analytics
    ports:
      - "5001:80"
  command:
    build:
      context: ./command
    image: command
    ports:
      - "5000:80"
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "4200:4200"
    image: dashboard
    # depends_on:
    #   - gateway
volumes:
  influxdata:
